version: "3.9"

services:
  rpa-app:
    build:
      context: ./docker-rpa
      dockerfile: Dockerfile
    container_name: rpa-app
    ports:
      - "5001:5001"
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
      - "/dev/video0:/dev/video0"
    environment:
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - SECRET_KEY=dev-secret-key
    volumes:
      - uploads:/app/uploads
      - ./docker-rpa/app/static:/app/static
      - certs:/app/certs

  logic2:
    build:
      context: ./docker-logic2
      dockerfile: Dockerfile
    container_name: logic2
    ports:
      - "8080:8080"
    privileged: true
    volumes:
      - uploads:/root/uploads
      - "./docker-logic2/shared:/root/shared"
    devices:
      - "/dev/bus/usb/002/003:/dev/bus/usb/002/003"
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - certs:/etc/nginx/certs
      - ./docker-rpa/app/static:/app/static
    depends_on:
      - rpa-app

volumes:
    uploads:
    certs: